# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

import pandas as pd
import plotly.express as px
import json
import numpy as np

# Cargar datos de porcentajes
porcentajes = (
    pd.read_csv('../datos/porcentajes.csv')
    .query('estado != "Estados Unidos Mexicanos"')
    .drop('Unnamed: 0', axis = 1)
    )

# Cargar GeoJSON
with open('../datos/states_simple.geojson', 'r', encoding='utf-8') as f:
    mexico_geojson = json.load(f)

# Cargar rezago
rezago = (
    pd.read_csv(
        '../datos/cuadro26A_rezago_educativo.csv', 
        skiprows = 9, usecols = range(2, 7)
        )
    .dropna(how = 'all')
    .rename({ 'Unnamed: 2': 'entidad', '2022**': '2022' }, axis = 1)
    .query('entidad != "Estados Unidos Mexicanos"')
    .set_index('entidad')
    .stack()
    .reset_index()
    .rename({'level_1': 'ano', 0: 'noasisten_notienen'}, axis = 1)
    .assign(ano = lambda x: x['ano'].astype(int))
)

# Cargar carencia

carencia = (
    pd.read_csv(
        '../datos/cuadro27_pobreza_porgrupo_etarios.csv',
        skiprows = 8, usecols = [2, 73, 74, 75, 76]
    )
    .dropna(how = 'all')
    .rename({ 
        'Unnamed: 2': 'entidad', 
        '2016.14': '2016', 
        '2018.14': '2018', 
        '2020.14': '2020', 
        '2022**.14': '2022' 
        }, axis = 1)
    .query('entidad != "Estados Unidos Mexicanos"')
    .set_index('entidad')
    .stack()
    .reset_index()
    .rename({'level_1': 'ano', 0: 'carencia_promedio'}, axis = 1)
    .assign(ano = lambda x: x['ano'].astype(int))
)

vars_porcentajes = {
    'porc_pob_3_21_no_asist_sin_oblig': 'Población de 3 a 21 años que no asiste a educación obligatoria', 
    'porc_pob_16mas_sin_secu': 'Población de 16 años o más sin educación secundaria', 
    'porc_pob_16mas_sin_prim': 'Población de 15 años o más sin educación primaria',
    'porc_tasa_inasistencia_3_15': 'Tasa de inasistencia de 3 a 15 años', 
    'porc_tasa_inasistencia_16_21': 'Tasa de inasistencia de 16 a 21 años', 
    'porc_seg_aliment': 'Porcentaje de seguridad alimentaria', 
    'porc_inseg_aliment_leve': 'Porcentaje de inseguridad alimentaria leve',
    'porc_inseg_aliment_mode': 'Porcentaje de inseguridad alimentaria moderada', 
    'porc_inseg_aliment_seve': 'Porcentaje de inseguridad alimentaria severa', 
    'porc_limit_consumo': 'porc_limit_consumo', # ¿Qué es esto?
    'porc_carencia_menor18_x': 'porc_carencia_menor18_x', # ¿Qué es esto?
    'porc_carencia_menor18_y': 'porc_carencia_menor18_y', # ¿Qué es esto?
    'porc_carencia_6_11_x': 'porc_carencia_6_11_x', # ¿Qué es esto?
    'porc_carencia_12_17_x': 'porc_carencia_12_17_x', # ¿Qué es esto?
    'porc_carencia_menor18': 'porc_carencia_menor18',# ¿Qué es esto?
    'porc_carencia_6_11_y': 'porc_carencia_6_11_y', # ¿Qué es esto?
    'porc_carencia_12_17_y': 'porc_carencia_12_17_y' # ¿Qué es esto?
}
anos = sorted(porcentajes['anio'].unique())
entidades = sorted(rezago['entidad'].unique())

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    from shinywidgets import output_widget

    output_widget('mapa')

    # ========================================================================

    output_widget('scatter')

    # ========================================================================

    ui.output_ui('brecha_3_15')

    # ========================================================================

    ui.output_ui('brecha_16_21')

    # ========================================================================

    from shiny import reactive, render
    from shinywidgets import render_widget

    # 1. Datos del mapa
    @reactive.calc
    def ano():
        return int(input.ano())

    @reactive.calc
    def datos_geografia():
        return porcentajes.query('anio == @ano')
    # print('{} por estado - {}'.format(vars_porcentajes[var_porcentaje], ano))

    @render_widget
    def mapa():
        var = input.var_porcentaje()
        df = datos_geografia()
        return px.choropleth(
            df,
            geojson = mexico_geojson,
            locations = 'estado',
            featureidkey = 'properties.NOMGEO',
            color = var,
            color_continuous_scale = "Reds",
            range_color = ( min(0, df[var].min()), max(25, df[var].max()) ),
            labels = {var: ''},
            fitbounds = "locations"
        )

    # 2. Datos del scatterplot
    @reactive.calc
    def rezago_carencia():
        ent = input.entidad()
        ano = input.ano()
        return (
            rezago
            .merge(carencia, on = ['entidad', 'ano'])
            .query('ano == @ano')
            .assign( color = lambda x: np.where(x['entidad'] == ent, 'Interés', '') )
            .rename(
                {'carencia_promedio': 'Carencia (%)', 
                'noasisten_notienen': 'Sin educación'}, axis = 1)
        )

    # print(
    #     'Carencia promedio ({:.1f}%), Niñas, niños y adolescentes no asisten y no tienen educación obligatoria ({:.0f}%)'
    #     .format(*rezago_carencia.query('entidad == @entidad').get(['Carencia (%)', 'Sin educación']).iloc[0].values)
    #     )

    @render_widget
    def scater():
        ent = input.entidad()
        df = rezago_carencia()
        return px.scatter(
            df, 
            x = 'Carencia (%)', 
            y = 'Sin educación', 
            text = np.where( df['entidad'] == ent, df['entidad'], '' ),
            hover_name = 'entidad',
            hover_data= ['Carencia (%)', 'Sin educación'],
            color = 'color', symbol = 'color', opacity = 0.5,
            trendline = 'ols'
            )

    # 3. Valueboxes
    @reactive.calc
    def brecha():
        ent = input.entidad()
        ano = input.ano()
        return porcentajes.query('anio == @ano & estado == @ent')

    @render.ui
    def brecha_3_15():
        val = brecha()['porc_tasa_inasistencia_3_15'].iloc[0]
        return ui.value_box(
            title = 'Inasistencia entre infancias (3 a 15 años)',
            value = '{:.1f}%'.format(val),
            showcase = ui.tags.i(class_ = 'bi bi-egg-fill'),
            theme = ui.vale_box_theme(bg = '#0860ED')
        )

    @render.ui
    def brecha_16_21():
        val = brecha()['porc_tasa_inasistencia_16_21'].iloc[0]
        return ui.value_box(
            title = 'Inasistencia entre juventudes (16 a 21 años)',
            value = '{:.1f}%'.format(val),
            showcase = ui.tags.i(class_ = 'bi bi-egg-fill'),
            theme = ui.vale_box_theme(bg = '#F3487E')
        )

    # 4. Pie
    @render_widget
    def pie():
        df = (
            brecha()
            .get([
                'porc_seg_aliment', 'porc_inseg_aliment_leve',
                'porc_inseg_aliment_mode', 'porc_inseg_aliment_seve'
            ])
            .rename({
                'porc_seg_aliment': 'Seguridad', 
                'porc_inseg_aliment_leve': 'Inseguridad leve',
                'porc_inseg_aliment_mode': 'Inseguridad moderada', 
                'porc_inseg_aliment_seve': 'Inseguridad severa'
            }, axis = 1)
            .unstack()
            .reset_index()
        )

        fig = px.pie(
            df, values = 0, names = 'level_0', color = 'level_0',
            color_discrete_map = {
                'Seguridad': 'green',
                'Inseguridad leve': 'yellow',
                'Inseguridad moderada': 'orange',
                'Inseguridad severa': 'red'
                }
        )

        fig.update_layout(showlegend = False)
        return fig

    # ========================================================================



    return None


_static_assets = ["HackODS_files","HackODS_files/libs/quarto-html/tippy.css","HackODS_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css","HackODS_files/libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css","HackODS_files/libs/bootstrap/bootstrap-icons.css","HackODS_files/libs/bootstrap/bootstrap-9b953ad8be9e480b4d58e863411a52d5.min.css","HackODS_files/libs/bootstrap/bootstrap-dark-9b953ad8be9e480b4d58e863411a52d5.min.css","HackODS_files/libs/clipboard/clipboard.min.js","HackODS_files/libs/quarto-html/quarto.js","HackODS_files/libs/quarto-html/tabsets/tabsets.js","HackODS_files/libs/quarto-html/axe/axe-check.js","HackODS_files/libs/quarto-html/popper.min.js","HackODS_files/libs/quarto-html/tippy.umd.min.js","HackODS_files/libs/quarto-html/anchor.min.js","HackODS_files/libs/bootstrap/bootstrap.min.js","HackODS_files/libs/quarto-dashboard/quarto-dashboard.js","HackODS_files/libs/quarto-dashboard/stickythead.js","HackODS_files/libs/quarto-dashboard/web-components.js","HackODS_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "HackODS.html",
    server,
    static_assets=_static_assets,
)
